layout_spectrum: 0.1382144
typography_spectrum: 0.4513492
color:
  saturation: 0.8201647
  lightness: 0.8607053
  brandStrength: 0.2564
  rhythmicContrast: 0.006383904
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: 'Yukonjak giant Alaskan malamutes '
